import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Home from './pages/Home';
import ServicesPage from './pages/ServicesPage';
import TrackingPage from './pages/TrackingPage';
import AboutUsPage from './pages/AboutUsPage';
import TrackingPageWithData from './pages/TrackingPageData';

const sampleJsonData = {
  "status": "Success",
  "message": "Tracking",
  "data": [
      {
          "id": 40,
          "customer": 1,
          "awb": 100000000041,
          "order_number": "UBTESTB2BTRNS0012",
          "consignee": {
              "id": 44,
              "name": "Ak Singh",
              "address": "B198 NPViii",
              "city": "Gurgaon",
              "state": "Haryana",
              "country": "",
              "pincode": 122017,
              "mobile": 9555541410,
              "address_type": "Home",
              "lat": 0.0,
              "lng": 0.0,
              "email": "akbiz247@gmail.com",
              "status": 1,
              "updated_on": null,
              "added_on": "2024-11-20T16:55:17.951293"
          },
          "origin": "Gurgaon DC - GDC",
          "destination": "Gurgaon DC - GDC",
          "current_sc": 1,
          "pickup_address": {
              "id": 36,
              "customer": {
                  "id": 1,
                  "name": "Urban Bolt",
                  "code": "C0001",
                  "logo": "",
                  "website": "www.urbanbolt.com",
                  "email": "urbanbolt@gmail.com",
                  "mobile": 123456789,
                  "fax": null,
                  "gst": "GJ686368593bjdg",
                  "pan": "ASDFGHJJJJ",
                  "address": "B-194 Sai Kunj New palam Vihar Gurgaaon Harayan",
                  "pincode": 122017,
                  "city": "Gurgaon",
                  "state": "Haryana",
                  "country": "India",
                  "lat": 0.0,
                  "lng": 0.0,
                  "bank_name": "HDFC Bank",
                  "account_number": "4567894567",
                  "ifsc": "HDFC000134",
                  "domestic": true,
                  "international": false,
                  "sub_user_limit": 10,
                  "updated_by_user": "",
                  "is_active": true,
                  "updated_on": null,
                  "added_on": "2024-10-02 22:01:34"
              },
              "address_type": "Seller",
              "name": "Shipper name - Test",
              "code": "PSA00136",
              "address": "Shipper address - Test",
              "city": "Test city",
              "state": "Test State",
              "country": "India",
              "pincode": 122017,
              "mobile": 1234567890,
              "lat": 0.0,
              "lng": 0.0,
              "email": "test@gmail.com",
              "updated_by_user": "",
              "default": false,
              "is_active": true,
              "updated_on": null,
              "added_on": "2024-11-18 23:15:56"
          },
          "return_address": "",
          "product_type": "PPD",
          "weight": 0.5,
          "length": 10.0,
          "breadth": 10.0,
          "height": 10.0,
          "volumetric_weight": 0.0,
          "collectable_value": 0.0,
          "declared_value": 99.0,
          "invoice_value": 0.0,
          "item_price": 99.0,
          "invoice_date": "2024-11-20",
          "item_description": "Nyka Lipstic",
          "pieces": 1,
          "item_quantity": 1,
          "invoice_number": "",
          "ref_awb": null,
          "edd": "2024-11-30T16:55:17.927189",
          "pod_url": "delivery_pods/GDC/2024/11/20/100000000041_2024-11-20-17-22-46.png",
          "item_hsn": "345678990",
          "item_sku": "SKU1234",
          "is_dg": false,
          "is_essential": false,
          "is_secure_delivery": false,
          "delivery_priority": false,
          "is_reverse": false,
          "is_surface": false,
          "is_air": false,
          "is_express": false,
          "courier_status_code": null,
          "remarks": null,
          "status_code": {
              "id": 14,
              "name": "Delivered",
              "code": "DDL",
              "description": "Delivered",
              "closure_code": true,
              "shipment_status": 8,
              "is_active": true,
              "updated_on": null,
              "added_on": "2024-10-03 02:10:43"
          },
          "sub_status_code": null,
          "is_closed": false,
          "status": 8,
          "is_remitted": false,
          "year": 2024,
          "month": 11,
          "updated_on": "2024-11-20T17:22:37",
          "last_updated_by": 4,
          "added_on": "2024-11-20T16:55:17.975501",
          "additional": [
              {
                  "id": 215,
                  "shipment": 40,
                  "key": "channelId",
                  "value": "Shopi",
                  "status": 1,
                  "updated_on": null,
                  "added_on": "2024-11-20T16:55:17.982125"
              }
          ],
          "step": 0,
          "scans": [
              {
                  "id": 178,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": "delivery_pods/GDC/2024/11/20/100000000041_2024-11-20-17-22-46.png",
                  "status_code": {
                      "id": 14,
                      "name": "Delivered",
                      "code": "DDL",
                      "description": "Delivered",
                      "closure_code": true,
                      "shipment_status": 8,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-03 02:10:43"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Delivered",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:22:37",
                  "pushed_on": null,
                  "status": 8,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 4,
                  "added_on": "2024-11-20 17:22:47"
              },
              {
                  "id": 177,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 12,
                      "name": "Out for Delivery",
                      "code": "OFD",
                      "description": "Out for Delivery",
                      "closure_code": false,
                      "shipment_status": 6,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-03 02:09:44"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Delivery Outscan Closed",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:16:30",
                  "pushed_on": null,
                  "status": 6,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 3,
                  "added_on": "2024-11-20 17:16:30"
              },
              {
                  "id": 176,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 20,
                      "name": "Delivery Scheduled",
                      "code": "DDS",
                      "description": "Delivery Scheduled",
                      "closure_code": false,
                      "shipment_status": 41,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-07 21:27:49"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Included in delivery oustscan",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:16:18",
                  "pushed_on": null,
                  "status": 41,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 3,
                  "added_on": "2024-11-20 17:16:18"
              },
              {
                  "id": 175,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 11,
                      "name": "Reached at DC",
                      "code": "RDC",
                      "description": "Reached at DC",
                      "closure_code": false,
                      "shipment_status": 5,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-03 02:09:03"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Inscanned",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:15:09",
                  "pushed_on": null,
                  "status": 5,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 3,
                  "added_on": "2024-11-20 17:15:09"
              },
              {
                  "id": 174,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": "pickup_pods/GDC/2024/11/20/100000000041_2024-11-20-17-11-00.png",
                  "status_code": {
                      "id": 4,
                      "name": "Picked Up",
                      "code": "PKD",
                      "description": "Picked Up",
                      "closure_code": false,
                      "shipment_status": 1,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-03 02:04:14"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Picked up",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:10:51",
                  "pushed_on": null,
                  "status": 1,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 4,
                  "added_on": "2024-11-20 17:11:01"
              },
              {
                  "id": 170,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 2,
                      "name": "Pickup Assigned",
                      "code": "PKA",
                      "description": "Pickup Assigned",
                      "closure_code": false,
                      "shipment_status": 32,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-03 02:03:17"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Pickup Outscan Closed",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:01:13",
                  "pushed_on": null,
                  "status": 32,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 3,
                  "added_on": "2024-11-20 17:01:13"
              },
              {
                  "id": 168,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 19,
                      "name": "Pickup Scheduled",
                      "code": "PKS",
                      "description": "Pickup Scheduled",
                      "closure_code": false,
                      "shipment_status": 31,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-06 23:54:20"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": "Included in pickup oustscan (OutscanID:14)",
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 17:00:19",
                  "pushed_on": null,
                  "status": 31,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": 3,
                  "added_on": "2024-11-20 17:00:19"
              },
              {
                  "id": 165,
                  "shipment": 40,
                  "current_sc": "Gurgaon DC - GDC",
                  "weight": null,
                  "edd": null,
                  "reference_awb": null,
                  "pieces": 0,
                  "lat": 0.0,
                  "lng": 0.0,
                  "chargeable_weight": 0.0,
                  "product_type": null,
                  "otp_verified": null,
                  "pod_url": null,
                  "status_code": {
                      "id": 1,
                      "name": "Manifest",
                      "code": "MAN",
                      "description": "Shipment Manifested",
                      "closure_code": false,
                      "shipment_status": 0,
                      "is_active": true,
                      "updated_on": null,
                      "added_on": "2024-10-02 23:30:59"
                  },
                  "sub_status_code": null,
                  "courier_status_code": null,
                  "remarks": null,
                  "push_status": false,
                  "scan_location": "Gurgaon DC - GDC",
                  "scan_date": "2024-11-20 16:55:17",
                  "pushed_on": null,
                  "status": 0,
                  "year": 2024,
                  "month": 11,
                  "updated_on": null,
                  "updated_by": null,
                  "added_on": "2024-11-20 16:55:18"
              }
          ]
}
]
}

function App() {
  return (
    <BrowserRouter>
      <div className="app">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/services" element={<ServicesPage />} />
          <Route path="/tracking" element={<TrackingPage />} />
          <Route path="/trackShip" element={<TrackingPageWithData jsonData={sampleJsonData} />} />
          <Route path="/about" element={<AboutUsPage />} />
        </Routes>
        
      </div>
    </BrowserRouter>
  );
}

export default App;